INSERT INTO "PUBLIC"."ACCOUNT_HOLDER"("CIF") VALUES('CIF1');

INSERT INTO "PUBLIC"."ACCOUNT"
("CIF", "ACCOUNT_NUMBER", "ACCOUNT_NAME", "ACCOUNT_TYPE", "BALANCE_DATE", "CURRENCY", "OPENING_AVAILABLE_BALANCE")
VALUES
    ('CIF1', '585309209', 'SGSavings726', 'SAVINGS', '2018-11-08', 'SGD', 84327.51);